### ISSUE TITLE
netcoreapp1.0 support

### ISSUE THREAD

**Issue by t2k** [WiredUK/Wired.Razor#1]
tried to install but, not supported in an aspnet core  app.

**Comment by WiredUK** [comment]
Yes, not supported in .Net Core just yet, after all, it hasn't even gone RTM yet. When it does, I may take a look and see how easy this is, but it relies on the dependencies also supporting .Net Core.

**Comment by t2k** [comment]
yep,  looks like iTextSharp dependencies are on the older aspnet bits.  I've been looking for a solution to render MVC views to PDF in an open source project using aspnet core.  I can lend a hand with testing if you are so inclined.

**Comment by SemperFu** [comment]
I just ran into this issue today with .Net 4.6.2. Main error is it using System.Web.MVC instead of Microsoft.AspNetCore.Mvc

**Comment by WiredUK** [comment]
Closing this as it requires third party libraries to migrate to .Net Core. If they update, I'll convert this library over.
