### ISSUE TITLE
Headers / Footers per page

### ISSUE THREAD

**Issue by stephenhendry** [WiredUK/Wired.Razor#2]
I have played around with this today and it looks very good. I want to try and generate some simple reports using this. One of the requirements I have is to have is to add a footer and header to each pdf page. i.e. Company logo on each page and page number in the footer. Can you think of a way to do this with the current setup?

**Comment by WiredUK** [comment]
It's just using Razor so you can have a Layout just as you would with a normal MVC view. So you could put the header/footer in the layout (you will need to set up the template as per the [docs](https://github.com/WiredUK/Wired.Razor/blob/master/README.md#something-a-bit-more-complicated))

You may be able to call the header/footer as a partial though I've not tried that. I'll try to give it a go though it may take me a few days before I have time.

**Comment by stephenhendry** [comment]
Looks like I can make use of `PageEvent` on the writer.

```
            var pdf = generator.GeneratePdf(
                (writer, document) =>
                {
                    writer.PageEvent = new HeaderFooter();
                }, 
                model, "Views/Test.cshtml");
```

You then add a class with

```
    public class HeaderFooter : PdfPageEventHelper
    {
        public override void OnEndPage(PdfWriter writer, Document document)
        {
          // Code here
        }

    }
```

I need to play around with the partial view inside the `OnEndPage`.

**Comment by WiredUK** [comment]
Oh yes of course, I didn't realise you wanted a footer per page. So yes, that's the correct way to do that, it's how I have achieved the same thing in the past. I should probably put that in the readme to make it a bit more obvious.

**Comment by stephenhendry** [comment]
Did you use partial views for the header and footers or did you have to use iTextSharp objects?

**Comment by WiredUK** [comment]
When I did it I needed a quick fix and had a very simple footer so ended up using iTextSharp objects. I would like to come up with a more consistent way of doing it though, but I've not had a chance to think about how to do it.

**Comment by stephenhendry** [comment]
iTextSharp objects are working great for the header (company logo) and footer (date). The last job that I need to do is force the creation of a new page.

Very nice project. It works well.

**Comment by stephenhendry** [comment]
`<div style="page-break-before:always">&nbsp;</div>` Works to create a new page :)

**Comment by WiredUK** [comment]
Ah yes, you beat me to answering that one, glad you like the package (even though I'm really just standing on the shoulders of giants!)

**Comment by WiredUK** [comment]
@stephenhendry Done some work over the last couple of days to get the footer (and header) situation functioning. I've committed the changes to the repo and I'll build a Nuget package to go with it now. Thanks for reminding me that I wanted to sort this one out! Hope you get a chance to try it.

**Comment by stephenhendry** [comment]
Thanks. I have updated the Nuget packages to the latest version. will need to do some refactoring of my code to switch over to it. Hope to change to it at some point this week.

**Comment by WiredUK** [comment]
Excellent, please do let me know how it goes, if it worked well and what you think might help improve it!

**Comment by stephenhendry** [comment]
I finally got round to converting the code over today. It works well :) Thank you for the update.

Only one more use case to try and work out. When outputting tabular data add a table header on each new page. I will have a think to see how I could implement it.
