### ISSUE TITLE
Does this honor style sheets?

### ISSUE THREAD

**Issue by mkgn** [WiredUK/Wired.Razor#3]
My view has styles defined in <head/> When viewing it in normal browser styles are applied properly.
However when I generate the PDF styles are not applied and it just outputs in black and white.

Is there a way to style the PDF preferably using the same stylesheet?

**Comment by WiredUK** [comment]
Absolutely yes it does. Depending on which method you have used to generate the PDF, you may have to use an absolute path for the CSS or embed the CSS directly on the page in a `style` tag. Unfortunately I'm unable to provide an example right now, but when I get a chance, I will update the sample app to show how it's done.

**Comment by breakcoding** [comment]
Please show an example with the style and dynamic images
