### ISSUE TITLE
Documentation new page

### ISSUE THREAD

**Issue by stephenhendry** [WiredUK/Wired.Razor#4]
Would you be able to add a few lines in the documentation on how to create a new page in a PDF.

You can of course use:

`<div style="page-break-before:always">&nbsp;</div>`

However, I always seem to have to Google it getting it from iTextSharp XML Worker library.

**Comment by WiredUK** [comment]
Sure, I'm happy to do this when I get some spare time (which may not be for a couple of weeks!) Alternatively, if you're up for it, you can create a pull request and add it yourself! It's just the [README.MD](https://github.com/WiredUK/Wired.Razor/blob/master/README.md) file that needs changing.

**Comment by stephenhendry** [comment]
Pull request added
